import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
const vendor="static/games/family-sudoku/vendor/robatron-sudoku.js", worker="static/games/family-sudoku/js/generator-worker.js";
const source=fs.readFileSync(vendor,"utf8"), workerSource=fs.readFileSync(worker,"utf8"), bank=JSON.parse(fs.readFileSync("static/games/family-sudoku/data/fallback-puzzles.json","utf8"));
function api(){const box={};vm.createContext(box);vm.runInContext(source,box);return box.sudoku}
test("pinned vendor and API are local",()=>{assert(fs.statSync(vendor).size>1000);assert(fs.statSync("static/games/family-sudoku/vendor/robatron-LICENSE.txt").size>0);const s=api();for(const name of ["generate","solve","get_candidates","validate_board"])assert.equal(typeof s[name],"function")});
test("Robatron solves fallback and generates all presets",{timeout:30000},()=>{const s=api();assert.equal(s.solve(bank.puzzles[0].puzzle),bank.puzzles[0].solution);for(const [difficulty,clues] of [["easy",62],["medium",53],["hard",44]]){const puzzle=s.generate(difficulty,true);assert.equal(puzzle.length,81);assert.equal((puzzle.match(/[1-9]/g)||[]).length,clues);const solution=s.solve(puzzle);assert.equal(solution,s.solve(puzzle,true));assert.match(solution,/^[1-9]{81}$/)}});
test("classic worker validates requests and response schema",{timeout:30000},()=>{const messages=[];const box={self:null,postMessage:(m)=>messages.push(m),importScripts:(path)=>{assert.equal(path,"../vendor/robatron-sudoku.js");box.self.sudoku=api()}};box.self=box;vm.createContext(box);vm.runInContext(workerSource,box);box.onmessage({data:{type:"generate",requestId:"r1",difficulty:"easy"}});assert.equal(messages[0].type,"generated");assert.equal(messages[0].requestId,"r1");messages.length=0;box.onmessage({data:{type:"generate",requestId:"r2",difficulty:"bad"}});assert.equal(messages[0].type,"error")});
test("static contract contains modal, responsive sizing, and local face resolution",()=>{const html=fs.readFileSync("templates/games/family_sudoku.html","utf8"),css=fs.readFileSync("static/games/family-sudoku/css/game.css","utf8"),js=fs.readFileSync("static/games/family-sudoku/js/game.mjs","utf8");assert.match(html,/data-picker/);assert.match(html,/data-faces-url/);assert.match(html,/meta name="robots"/);assert.match(css,/760px/);assert.match(css,/720px/);assert.match(css,/100dvh/);assert.match(css,/z-index:\s*1100/);assert.match(css,/repeat\(3,\s*1fr\)/);assert.match(js,/new URL\(root\.dataset\.facesUrl/);assert.match(js,/faces\.faces\.forEach/);assert.match(js,/document\.body\.style\.overflow/);assert.match(js,/\.terminate\(\)/);assert.match(js,/fallback/)});
